classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.virtual-mcp11-k8s-calico-aws
parameters:
  salt:
    minion:
      cert:
        k8s_client:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_proxy:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_scheduler:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_controller_manager:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}

  docker:
    host:
      pkgs:
      - docker-ce=17.03.2~ce-0~ubuntu-xenial
      - python-docker
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    system:
      kernel:
        sysctl:
          vm.max_map_count: 262144
    network:
      resolv:
        dns:
        - 10.254.0.10
        - 8.8.8.8
        - 8.8.4.4
