classes:
- service.etcd.server.cluster
#- service.helm.client
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- cluster.virtual-mcp11-k8s-calico-aws.kubernetes.compute
- cluster.virtual-mcp11-k8s-calico-aws.kubernetes.certs
#- cluster.virtual-mcp11-k8s-calico-aws.kubernetes.rbac
#- cluster.virtual-mcp11-k8s-calico-aws.kubernetes.podpreset
- cluster.virtual-mcp11-k8s-calico-aws
parameters:
  _param:
    keepalived_vip_interface: eth0
    keepalived_vip_virtual_router_id: 60
    kubernetes_apiserver_port: 4430
  salt:
    minion:
      cert:
        etcd_server:
          alternative_names: IP:127.0.0.1,DNS:${_param:cluster_vip_address},IP:${_param:cluster_local_address},DNS:${linux:system:name},DNS:${linux:network:fqdn}
        k8s_proxy:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_scheduler:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_controller_manager:
          alternative_names: DNS:${_param:cluster_vip_address},IP:${_param:cluster_node01_address},IP:${_param:cluster_node02_address},IP:${_param:cluster_node03_address},IP:${_param:kubernetes_internal_api_address}

#  helm:
#    client:
#      repos:
#        mirantisworkloads: https://mirantisworkloads.storage.googleapis.com/
#      releases:
#        prometheus:
#          name: prometheus
#          chart: mirantisworkloads/prometheus
#          namespace: kube-system
  etcd:
    server:
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      apiserver:
        secure_port: ${_param:kubernetes_apiserver_port}
      etcd:
        ssl:
          enabled: true
      network:
        etcd:
          ssl:
            enabled: true
      namespace:
        netchecker:
          enabled: true
    common:
      addons:
        storageclass:
          slow_aws:
            name: standard
            default: True
            provisioner: aws-ebs
            type: gp2
  haproxy:
    proxy:
      listen:
        k8s_secure:
          enabled: false
        k8s_secure_aws:
          type: kubernetes
          options:
            - ssl-hello-chk
          binds:
          - address: ${_param:cluster_local_address}
            port: 443
          servers:
          - name: ${_param:cluster_node01_hostname}
            host: ${_param:cluster_node01_address}
            port: ${_param:kubernetes_apiserver_port}
            params: check
          - name: ${_param:cluster_node02_hostname}
            host: ${_param:cluster_node02_address}
            port: ${_param:kubernetes_apiserver_port}
            params: check
          - name: ${_param:cluster_node03_hostname}
            host: ${_param:cluster_node03_address}
            port: ${_param:kubernetes_apiserver_port}
            params: check

  keepalived:
    cluster:
      enabled: false
      instance:
        VIP:
          unicast_src_ip: ${_param:cluster_local_address}
          unicast_peer:
            - ${_param:cluster_node01_address}
            - ${_param:cluster_node02_address}
            - ${_param:cluster_node03_address}
