classes:
- system.linux.system.single
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.ubuntu
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 10.0.10.10
    infra_config_deploy_address: 10.0.10.10

    cluster_domain: virtual-mcp11-k8s-calico.local
    cluster_name: virtual-mcp11-k8s-calico
    apt_mk_version: nightly
  linux:
    network:
      resolv:
        dns:
          - 10.0.0.2
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      user:
        ubuntu:
          name: 'Workshop user'
          enabled: true
          sudo: true
          full_name: 'Ubuntu User'
          home: '/home/ubuntu'
          password: '$6$VsjbU/n9xiYWdvm6$/rEfLSjh3R1lWpV31KL30m0BPvfZudq/hBB3b/JC/Xw96FN2Sepm0qGkKCiun50dglh5AzHB2vmalsPGN5EaJ0'
  openssh:
    server:
      password_auth: true
